steps:
  - name: bash
    args:
      - rm
      - "-rf"
      - ../configs
  - name: bash
    args:
      - rm
      - "-rf"
      - ./configs/*
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - configs
      - configs.build
  - name: bash
    args:
      - cp
      - "-R"
      - ./configs.build/mirror-media/mirror-media-nuxt/gcskeyfile.json
      - ./gcskeyfile.json
  - name: bash
    args:
      - cp
      - "-R"
      - ./configs.build/mirror-media/mirror-media-nuxt/$BRANCH_NAME/config.js
      - ./configs/config.js
  - name: bash
    args:
      - rm
      - "-R"
      - ./configs.build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/${PROJECT_ID}/mirror-media-nuxt:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/mirror-media-nuxt
timeout: 1800s
images:
  - gcr.io/$PROJECT_ID/mirror-media-nuxt
