steps:
  - name: bash
    args:
      - rm
      - "-rf"
      - ../configs
  - name: bash
    args:
      - rm
      - "-rf"
      - ./configs/*
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - configs
      - configs.build
  - name: bash
    args:
      - cp
      - "-R"
      - ./configs.build/mirror-media/mirror-media-nuxt/gcskeyfile.json
      - ./gcskeyfile.json
  - name: bash
    args:
      - cp
      - "-R"
      - ./configs.build/mirror-media/mirror-media-nuxt/dev/config.js
      - ./configs/config.js
  - name: bash
    args:
      - rm
      - "-R"
      - ./configs.build
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination="gcr.io/mirrormedia-1470651750304/mirror-media-nuxt:ci"
      - --verbosity=trace
      - --cache=true
      - --cache-ttl=672h
timeout: 1800s
serviceAccount: mirrormedia-1470651750304@cloudbuild.gserviceaccount.com
