<template>
  <div :id="`compass-fit-${unitId}`" class="micro-ad" />
</template>

<script>
export default {
  name: 'MicroAd',
  props: {
    unitId: {
      type: String,
      required: true,
    },
  },
  mounted() {
    this.insertScript()
  },
  beforeDestroy() {
    this.removeScript()
  },
  methods: {
    insertScript() {
      const microAdScript = document.createElement('script')
      microAdScript.id = `compass-fit-script-${this.unitId}`
      microAdScript.type = 'text/javascript'
      microAdScript.charset = 'UTF-8'
      microAdScript.async = true
      microAdScript.src =
        (document.location.protocol === 'https:' ? 'https://' : 'http://') +
        `nt.compass-fit.jp/lift_widget.js?adspot_id=${this.unitId}`
      document.head.appendChild(microAdScript)
    },
    removeScript() {
      const microAdScript = document.querySelector(
        `#compass-fit-script-${this.unitId}`
      )
      microAdScript && microAdScript.remove()
      const autoGeneratedScript = document.querySelector(
        `script[src*="${this.unitId}"`
      )
      autoGeneratedScript && autoGeneratedScript.remove()
      const microAdStyle = [
        ...document.querySelectorAll('style'),
      ].find((item) => item.textContent.includes(`#compass-fit-${this.unitId}`))
      microAdStyle && microAdStyle.remove()
    },
  },
}
</script>
