<template>
  <div v-if="!IS_AD_DISABLE" :id="`compass-fit-${unitId}`" class="micro-ad" />
</template>

<script>
import { IS_AD_DISABLE } from '~/configs/config.js'

export default {
  name: 'MicroAd',
  props: {
    unitId: {
      type: String,
      required: true,
    },
  },

  data() {
    return {
      IS_AD_DISABLE,
    }
  },

  mounted() {
    this.insertScript()
  },
  beforeDestroy() {
    this.removeScript()
  },
  methods: {
    insertScript() {
      const microAdScript = document.createElement('script')
      microAdScript.id = `compass-fit-script-${this.unitId}`
      microAdScript.type = 'text/javascript'
      microAdScript.charset = 'UTF-8'
      microAdScript.async = true
      microAdScript.src =
        (document.location.protocol === 'https:' ? 'https://' : 'http://') +
        `nt.compass-fit.jp/lift_widget.js?adspot_id=${this.unitId}`
      document.head.appendChild(microAdScript)
    },
    removeScript() {
      const microAdScript = document.querySelector(
        `#compass-fit-script-${this.unitId}`
      )
      microAdScript?.remove()

      const autoGeneratedScript = document.querySelector(
        `script[src*="${this.unitId}"`
      )
      autoGeneratedScript?.remove()

      const microAdStyle = [
        ...document.querySelectorAll('style'),
      ].find((item) => item.textContent.includes(`#compass-fit-${this.unitId}`))
      microAdStyle?.remove()
    },
  },
}
</script>

<style lang="scss" scoped>
/**
 * 請把樣式寫在 ~/css/micro-ad/ 資料夾中，再把樣式引入到需要它的元件內
 */
</style>
