<template>
  <div v-if="!IS_AD_DISABLE" :id="`compass-fit-${unitId}`" class="micro-ad" />
</template>

<script>
import { IS_AD_DISABLE } from '~/configs/config.js'

export default {
  name: 'MicroAd',
  props: {
    unitId: {
      type: String,
      required: true,
    },
  },

  data() {
    return {
      IS_AD_DISABLE,
    }
  },

  mounted() {
    this.insertScript()
  },
  beforeDestroy() {
    this.removeScript()
  },
  methods: {
    insertScript() {
      const microAdScript = document.createElement('script')
      microAdScript.id = `compass-fit-script-${this.unitId}`
      microAdScript.type = 'text/javascript'
      microAdScript.charset = 'UTF-8'
      microAdScript.async = true
      microAdScript.src =
        (document.location.protocol === 'https:' ? 'https://' : 'http://') +
        `nt.compass-fit.jp/lift_widget.js?adspot_id=${this.unitId}`
      document.head.appendChild(microAdScript)
    },
    removeScript() {
      const microAdScript = document.querySelector(
        `#compass-fit-script-${this.unitId}`
      )
      microAdScript && microAdScript.remove()
      const autoGeneratedScript = document.querySelector(
        `script[src*="${this.unitId}"`
      )
      autoGeneratedScript && autoGeneratedScript.remove()
      const microAdStyle = [
        ...document.querySelectorAll('style'),
      ].find((item) => item.textContent.includes(`#compass-fit-${this.unitId}`))
      microAdStyle && microAdStyle.remove()
    },
  },
}
</script>

<style lang="scss" scoped>
.micro-ad {
  &::v-deep {
    // Listing MicroAd Style
    #compass-fit-widget-content {
      .listArticleBlock__figure {
        position: relative;
        a {
          display: block;
          position: relative;
          padding-top: 66.66%;
          img {
            position: absolute;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
          }
        }
        .listArticleBlock__figure--colorBlock {
          position: absolute;
          left: 0;
          bottom: 0;
          padding: 8px;
          line-height: 1;
          font-size: 16px;
          color: white;
          display: inline-block;
          max-width: 100%;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
      }
      .listArticleBlock__content {
        flex: 1 1 auto;
        display: flex;
        flex-direction: column;
        padding: 15px 30px;
        text-align: justify;
        h2 {
          color: #34495e;
          font-size: 20.8px;
          font-weight: 300;
          line-height: 1.3;
        }
        p {
          display: -webkit-box;
          -webkit-box-orient: vertical;
          margin: 10px 0 0 0;
          color: #999;
          font-size: 16px;
          font-weight: 300;
          line-height: 1.5;
          word-wrap: break-word;
          -webkit-line-clamp: 3;
          overflow: hidden;
        }
      }
    }
  }
}
</style>
