query fetchMemberSubscriptions($firebaseId: String!) {
  member(where: { firebaseId: $firebaseId }) {
    firebaseId
    email
    type
    tos
    subscription(orderBy: [{ periodEndDatetime: desc }]) {
      id
      orderNumber
      frequency
      periodFirstDatetime
      postId
      paymentMethod
      oneTimeEndDatetime
      isActive
      periodEndDatetime
      periodNextPayDatetime
      newebpayPayment(orderBy: [{ paymentTime: desc }]) {
        paymentMethod
        paymentTime
        amount
        cardInfoLastFour
      }
    }
  }
}
query fetchMemberBasicInfo($firebaseId: String!) {
  member(where: { firebaseId: $firebaseId }) {
    id
    firebaseId
    email
    type
    tos
  }
}

query fetchSubscriptionPayments($firebaseId: String!) {
  member(where: { firebaseId: $firebaseId }) {
    email
    subscription(orderBy: [{ periodEndDatetime: desc }]) {
      orderNumber
      frequency
      periodEndDatetime
      paymentMethod
    }
  }
}
