query fetchMemberSubscriptions($firebaseId: String) {
  member(where: { firebaseId: $firebaseId }) {
    firebaseId
    email
    type
    subscription(orderBy: [{ periodFirstDatetime: desc }]) {
      orderNumber
      frequency
      postId
      paymentMethod
      oneTimeEndDatetime
      isActive
      periodEndDatetime
      periodNextPayDatetime
      newebpayPayment(orderBy: [{ paymentTime: desc }]) {
        paymentMethod
        paymentTime
        amount
        cardInfoLastFour
      }
    }
  }
}
query fetchMemberBasicInfo($firebaseId: String) {
  member(where: { firebaseId: $firebaseId }) {
    id
    firebaseId
    email
    type
    tos
  }
}

mutation setMemberTosToTrue($firebaseId: ID!) {
  updatemember(firebaseId: $firebaseId, data: { tos: true }) {
    firebaseId
    email
    type
    tos
  }
}
