query fetchMemberSubscriptions($firebaseId: String) {
  member(where: { firebaseId: $firebaseId }) {
    firebaseId
    email
    subscription(orderBy: [{ periodFirstDatetime: desc }]) {
      orderNumber
      frequency
      postId
      paymentMethod
      oneTimeEndDatetime
      newebpayPayment {
        paymentMethod
        paymentTime
        amount
        cardInfoLastFour
      }
    }
  }
}
