query magazineOrder($orderNumber: String!) {
  allMagazineOrders(where: { orderNumber: $orderNumber }) {
    id
    orderNumber
    purchaseDatetime
    merchandise {
      name
      code
      price
    }
    itemCount
    totalAmount
    purchaseName
    purchaseEmail
    purchaseMobile
    purchaseAddress
    receiveName
    receiveMobile
    receiveAddress
    createdAt
    totalAmount
    promoteCode
  }
}
