# query ($firebaseId: String!){
#   member(firebaseId: $firebaseId) {
#     firebaseId
#     email
#     name
#     gender
#     birthday
#     phone
#     country
#     city
#     district
#     address
#   }
# }
query fetchMemberProfile($firebaseId: String!) {
  member(where: { firebaseId: $firebaseId }) {
    id
    firebaseId
    email
    name
    gender
    birthday
    phone
    country
    city
    district
    address
  }
}
